### ISSUE TITLE
Setup up coding/dev environment

### ISSUE THREAD

**Issue by shen0083** [LilianDu/AHometoShare#12]

**Comment by clabelle21** [comment]
Having issues regarding NetBeans recognizing package javax.servlet.http. Might be related to my version of java being standard edition and not enterprise. I will investigate further.

**Comment by LilianDu** [comment]
Please pull the newest project and make sure everything works well.
Also, please follow Xia's database setup instruction. I tried. Everything is ok.
Thanks.

**Comment by clabelle21** [comment]
> 
> 
> Having issues regarding NetBeans recognizing package javax.servlet.http. Might be related to my version of java being standard edition and not enterprise. I will investigate further.

Issue has been resolved. Database setup is complete and newest code from pull runs successfully.

**Comment by LilianDu** [comment]
Okay, I think it is good to close. If everyone has something wrong, you can ask me. Thanks
