### ISSUE TITLE
Create Non-Functional Requirements for SRS

### ISSUE THREAD

**Issue by MRajjy** [LilianDu/AHometoShare#16]
See SRS Template and course powerpoint for more information on non-functional requirements

**Comment by clabelle21** [comment]
SWNF1. Have a target completion deadline of November 30 2018.
SWNF2. Display a visual theme consisting of a colour scheme, logos, pictures and other media provided by client.
SWNF3. Provide users with a simple and user-friendly interface.
SWNF4. Provide documentation to support user navigation.
SWNF5. Have service outages dealt with by the client’s hosting service.
SWNF6. Sustain the expected volume of users and provide appropriate response times.
SWNF7. Password protect users, who’s sensitive information will be encrypted.
SWNF8. Be created under the guidance of the Algonquin College Code of Ethics.
SWNF9. Support all conventional web browsers, including Mozilla Firefox, Google Chrome, Opera, and Internet Explorer.
