### ISSUE TITLE
Enable email notifications

### ISSUE THREAD

**Issue by LilianDu** [LilianDu/AHometoShare#174]

**Comment by clabelle21** [comment]
Enabled.

**Comment by clabelle21** [comment]
Created class EmailFactory which has static methods for sending confirmation email and password reset. I've only implemented the method confirmation email.

**Comment by clabelle21** [comment]
Everyone who pulls this commit will need to add javax.mail.jar to the build path. The jar can be found at:
https://algonquinlivecom-my.sharepoint.com/:u:/g/personal/labe0183_algonquinlive_com/ETBHPhhPdghGvPR03o5TKGwBzXCQ6yAVNfmyRBgUhSz1yw?e=6GO9ye

**Comment by clabelle21** [comment]
To add to build path:
1. Right click on AHomeToShare project.
2. Click properties (at bottom)
3. Click on 'Libraries' in sidebar
4. Click 'Add JAR/Folder'
5. Select jar file that you downloaded.

![image](https://user-images.githubusercontent.com/31929113/48318151-15ff2f80-e5ca-11e8-936e-af8a3cfe5fbc.png)
