### ISSUE TITLE
Create demo presentation

### ISSUE THREAD

**Issue by LilianDu** [LilianDu/AHometoShare#176]
Demonstration (1 hr.):  The rehearsed final demonstration of the product will follow the same demonstration format of a 15-minute demonstration by the team, in which all functionality of the fully integrated working product is reviewed.  Emphasis on the main product features, robustness of the product and security should be made through tracking (on the production device) the story of how the user will work with the system and highlights of various error handling scenarios.  
Each team member must bring their Student ID, laptop, be prepared to execute the team’s product and be prepared to describe their coding contribution, during the 40-minute discussion, following the demonstration.
Observations during the demonstration, the system overview report’s source code listing and the team’s project management dashboard peer review will be used to evaluate individual team members.

**Comment by MRajjy** [comment]
Ensure there is a CONCLUSION however NO RETROSPECTIVE
intro to team, intro to project, key functionalities, product demo, finally conclusion (15 mins hard stop)
