### ISSUE TITLE
Host Registration form - invalid phone number message 

### ISSUE THREAD

**Issue by MRajjy** [LilianDu/AHometoShare#206]
![bug_hostregistration_invalidnumber-message](https://user-images.githubusercontent.com/31902119/48787566-10cf6e00-ecb7-11e8-805f-5a984e25a852.JPG)

Test was in Internet Explorer.

Entering a invalid data (all letters) into the phone number field in host registration form provides error message (good); however it states "You must use this format:" - should specify the format after the colon or change the message

**Comment by LilianDu** [comment]
![image](https://user-images.githubusercontent.com/31700677/48982152-8919a300-f0ac-11e8-96b8-04c9e3b4fd0c.png)
