### ISSUE TITLE
Remove renting details from Renter Profile

### ISSUE THREAD

**Issue by MRajjy** [LilianDu/AHometoShare#207]
![rentingdetails-renter](https://user-images.githubusercontent.com/31902119/48790524-8dfde180-ecbd-11e8-8f5d-bac949af683e.JPG)

This is not currently used and is redundant as we have renter search capabilities for properties

**Comment by clabelle21** [comment]
Gone.
![image](https://user-images.githubusercontent.com/31929113/48955750-5ee5ab00-ef1d-11e8-9ce1-cdd5f7a94008.png)
