### ISSUE TITLE
Create SRS (Software Requirements)

### ISSUE THREAD

**Issue by shen0083** [LilianDu/AHometoShare#7]

**Comment by MRajjy** [comment]
Chris and I have completed the SRS. It is to be sent to the client for signature/approval, signed by the team and then submitted by Friday Oct 5 at 10am

**Comment by clabelle21** [comment]
SRS has been signed by all team members and clients. Sent to Anu on October 03. Can be found at: https://algonquinlivecom-my.sharepoint.com/:b:/g/personal/labe0183_algonquinlive_com/EYLP5w4njwJLuKAN9fGaycMBEu3E63keYVjgIUH8AKCn1Q?e=xtzsf6
