### ISSUE TITLE
Investigate setting Initial Context to run JUnit test cases

### ISSUE THREAD

**Issue by MRajjy** [LilianDu/AHometoShare#74]

**Comment by clabelle21** [comment]
Investigated. Still cannot get it working. I read about implementing Mockito framework but it seems there is no solution without setting up project with persistence and maven. Maybe we can ask Mike in our lab on Wednesday night?

**Comment by clabelle21** [comment]
Inquired about issue with Mike (Java lab instructor). He proposed a solution that is high in complexity and not guaranteed to work. I recommend that we import whatever tests we can into Eclipse and test them there.

**Comment by clabelle21** [comment]
Abandoning this method of J-unit testing. Instead will be creating test cases automatically with netbeans and running them in Eclipse with a different data source. See ticket #170 for further details.
