### ISSUE TITLE
Develop hostRegister.html

### ISSUE THREAD

**Issue by clabelle21** [LilianDu/AHometoShare#96]

**Comment by EXIT2652** [comment]
1) Added Host & Renter toggle in the "Sign Up" pop-up window to link the registration form accordingly:
   - When "Host" is selected and "Sign up with email" is clicked, the page will be link to hostRegister.html;
   - When "Renter" is selected and "Sign up with email" is clicked, the page will be link to renterRegister.html;
2) Fixed the "Sign Up" pop-up window layout for both "hostRegister.html" and "renterRegister.html" 
3) Added renterRegister.html content
